### ISSUE TITLE
PHP fatals not anymore ignored by @ operator: 2 bugs with pgsql and PDO pgsql and PHP8.0

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#666]
From https://www.php.net/releases/8.0/en.php :
`The @ operator no longer silences fatal errors. `

Testscript adodbtest-pgsql.php

```php
<?php
include_once "./vendor/adodb/adodb-php/adodb.inc.php";
$conf=array(
        array(
                'dbtype' => 'pgsql',
                'dbhost' => 'localhost',
                'dbname' => 'adodbtest',
                'dbuser' => 'adodbtest',
                'dbpassword'=> 'adodbtest',
        ),
        array(
                'dbtype' => 'pdo',
                'dbhost' => 'pgsql:host=localhost;dbname=adodbtest', # dsn
                'dbname' => null,
                'dbuser' => 'adodbtest',
                'dbpassword'=> 'adodbtest',
        ),
);

foreach ($conf as $c) {
        testMetaType($c);
}

function testMetaType($c) {
        $db = ADONewConnection($c['dbtype']);
        #$db->debug=true;
        $connect=$db->connect($c['dbhost'], $c['dbuser'], $c['dbpassword'], $c['dbname']);
        # error with pdo pgsql
        $serverinfo=$db->serverInfo();
        var_dump($serverinfo);

        # error with pgsql
        $mt=$db->metaType('INTEGER');
        var_dump($mt);
}
```

```
root@deb10-php8:/var/www/html/fsm# php7.3 adodbtest-pgsql.php
Array
(
    [description] => PostgreSQL 11.9 (Debian 11.9-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
    [version] => 11.9
)
IArray
(
    [description] => PostgreSQL 11.9 (Debian 11.9-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
    [version] => 11.9
)
Iroot@deb10-php8:/var/www/html/fsm# php8.0 adodbtest-pgsql.php 
Array
(
    [description] => PostgreSQL 11.9 (Debian 11.9-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
    [version] => 11.9
)
IPHP Fatal error:  Uncaught Error: Attempt to assign property "debug" on null in /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-pdo.inc.php:499
Stack trace:
#0 /var/www/html/fsm/vendor/adodb/adodb-php/adodb.inc.php(1263): ADODB_pdo->_query()
#1 /var/www/html/fsm/vendor/adodb/adodb-php/adodb.inc.php(1241): ADOConnection->_Execute()
#2 /var/www/html/fsm/vendor/adodb/adodb-php/adodb.inc.php(1681): ADOConnection->Execute()
#3 /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-pdo_pgsql.inc.php(116): ADOConnection->GetOne()
#4 /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-pdo.inc.php(256): ADODB_pdo_pgsql->serverInfo()
#5 /var/www/html/fsm/adodbtest-pgsql.php(29): ADODB_pdo->ServerInfo()
#6 /var/www/html/fsm/adodbtest-pgsql.php(21): testMetaType()
#7 {main}
  thrown in /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-pdo.inc.php on line 499
PHP Fatal error:  Uncaught TypeError: pg_free_result(): Argument #1 ($result) must be of type resource, bool given in /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-postgres64.inc.php:1054
Stack trace:
#0 /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-postgres64.inc.php(1054): pg_free_result()
#1 /var/www/html/fsm/vendor/adodb/adodb-php/adodb.inc.php(4037): ADORecordSet_postgres64->_close()
#2 /var/www/html/fsm/vendor/adodb/adodb-php/adodb.inc.php(3353): ADORecordSet->Close()
#3 [internal function]: ADORecordSet->__destruct()
#4 {main}
  thrown in /var/www/html/fsm/vendor/adodb/adodb-php/drivers/adodb-postgres64.inc.php on line 1054
```

(fiddled a bit within ADOdb 5.20.19 sources, so line numbers not exact.)

**Comment by dregad** [comment]
Just noticed as I was merging the hotfix/5.20 branch into master, that the issue in adodb-pdo.inc.php was actually fixed nearly 5 years ago... See #248
