### ISSUE TITLE
[mysqli] Regression in 5.22.0

### ISSUE THREAD

**Issue by recipe** [ADOdb/ADOdb#798]
Problem:
--
The following code  has worked well in `adodb` < 5.22.0. The most recent version introduced a regression.
```php
<?php
include __DIR__ . "/../../vendor/adodb/adodb-php/adodb.inc.php";
$db = ADONewConnection("mysqli://foo:bar@127.0.0.1:6280/foo");
$foo = $db->GetOne("SHOW TABLES FROM `foo` LIKE ?", ['settings']);
var_dump($foo);
```
Actual result:
--
```bash
[root@27dc2b3cb4a6 foo]# php app/www/_tests.php
SQL Statement failed on preparation: SHOW TABLES FROM `foo` LIKE ?'
bool(false)
```

More info with the custom error_handler:
```bash
[root@27dc2b3cb4a6 foo]# php app/www/_tests.php | sed 's/ #/\n#/g'
Feb 09 21:00:13 +00:00 - ADODB@3742 - INFO - ADOdb message: SQL Statement failed on preparation: SHOW TABLES FROM `foo` LIKE ?' Stack trace: 
#0 /usr/local/src/foo/vendor/adodb/adodb-php/adodb.inc.php(781): {closure}('SQL Statement f...', true)  
#1 /usr/local/src/foo/vendor/adodb/adodb-php/adodb.inc.php(994): ADOConnection::outp('SQL Statement f...')  
#2 /usr/local/src/foo/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php(1209): ADOConnection->outp_throw('SQL Statement f...', 'Execute')  
#3 /usr/local/src/foo/vendor/adodb/adodb-php/adodb.inc.php(1539): ADODB_mysqli->_query('SHOW TABLES FRO...', Array)  
#4 /usr/local/src/foo/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php(1135): ADOConnection->_Execute('SHOW TABLES FRO...', Array)  
#5 /usr/local/src/foo/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php(299): ADODB_mysqli->execute('SHOW TABLES FRO...', Array)  
#6 /usr/local/src/foo/app/www/_tests.php(4): ADODB_mysqli->GetOne('SHOW TABLES FRO...', Array)  
#7 {main}
/usr/local/src/foo/app/www/_tests.php:5:
bool(false)
```

Expected result:
--
The ``SHOW TABLES FROM `foo` LIKE 'settings';`` SQL statement should be executed.

Environment
--
```
[root@27dc2b3cb4a6 foo]# php -v
PHP 8.1.2 (cli) (built: Feb  9 2022 00:50:39) (NTS DEBUG)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by recipe** [comment]
```
adodb/adodb-php [3c8d1e5f] » git bisect good
a4b5110cf0740225caa345e969b1fcfefe7000a2 is the first bad commit
commit a4b5110cf0740225caa345e969b1fcfefe7000a2
Author: Mark Newnham <mark@newnhams.com>
Date:   Sat Jan 23 15:08:50 2021 -0700

    Add support for bound variable statements in MySQL (#655)
    
    Adds support for true bound variables in prepared statements in the mysqli driver.. Bound variable statement  now use mysqli_statement_execute instead of an emulated form.

 drivers/adodb-mysqli.inc.php | 231 ++++++++++++++++++++++++++++++++++++++++++-
 1 file changed, 227 insertions(+), 4 deletions(-)
```

**Comment by recipe** [comment]
Ok. I see it started using native `mysqli::prepare`, hence the error. Need to rewrite a bunch of PHP code or stay at `adodb` 5.21.4.

**Comment by mnewnham** [comment]
So I can see that you are creating a sort of 'Fake' bind statement, and allowing the emulated mode of prior versions turn it into a statement acceptable to mysql. Obviously we can never turn it into a proper prepared statement acceptable to mysql. Must admit, its something I never thought of. @dregad . what do you think of a "compatibility" mode. The emulated mode has been there for a long time after it should have been but I do think this is a bit of an edge case. The idea would be to drop the old section of code back in and add a ``$db->useOldBindMode = true`` type statement

**Comment by recipe** [comment]
I will do. Issue can be closed.

**Comment by dregad** [comment]
Thanks for your feedback and understanding.
